/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ligant.backend

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertEquals(classUnderTest.greeting, "Hello World!")
    }
}
